import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { cookies } from 'next/headers';
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  BorderStyle,
  ShadingType,
} from 'docx';
import * as fs from 'fs';
import * as path from 'path';

// GET list of generated reports
export async function GET(request: NextRequest) {
  try {
    const cookieStore = await cookies();
    const sessionUserId = cookieStore.get('session_user')?.value;
    if (!sessionUserId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const user = await db.user.findUnique({ where: { userId: sessionUserId } });
    if (!user || user.role !== 'admin') return NextResponse.json({ error: 'Admin access required' }, { status: 403 });

    const reportsDir = path.join(process.cwd(), 'download');
    if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });

    const files = fs.readdirSync(reportsDir)
      .filter(f => f.endsWith('.docx'))
      .map(f => {
        const stat = fs.statSync(path.join(reportsDir, f));
        return { name: f, size: stat.size, createdAt: stat.birthtime, path: `/api/reports/download?file=${encodeURIComponent(f)}` };
      })
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

    return NextResponse.json({ reports: files });
  } catch (error) {
    console.error('Get reports error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

// POST generate a new report
export async function POST(request: NextRequest) {
  try {
    const cookieStore = await cookies();
    const sessionUserId = cookieStore.get('session_user')?.value;
    if (!sessionUserId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const user = await db.user.findUnique({ where: { userId: sessionUserId } });
    if (!user || user.role !== 'admin') return NextResponse.json({ error: 'Admin access required' }, { status: 403 });

    const body = await request.json().catch(() => ({}));
    const reportType = body.reportType || 'full';

    // Fetch all notices
    const notices = await db.notice.findMany({
      where: { status: { not: 'deleted' } },
      include: { publishedBy: { select: { userId: true, name: true } } },
      orderBy: { createdAt: 'desc' },
    });

    // Fetch all requests (events/notices requested by users)
    const requests = await db.request.findMany({
      orderBy: { createdAt: 'desc' },
    });

    const now = new Date();
    const generatedAt = now.toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
    const generatedBy = user.name || user.userId;

    // Build document
    const children: (Paragraph | Table)[] = [];

    // Title
    children.push(
      new Paragraph({
        text: 'Notice Board — Full Report',
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
        spacing: { after: 200 },
      }),
      new Paragraph({
        children: [
          new TextRun({ text: `Generated on: ${generatedAt}`, size: 20, color: '555555' }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 100 },
      }),
      new Paragraph({
        children: [
          new TextRun({ text: `Generated by: ${generatedBy}`, size: 20, color: '555555' }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 400 },
      }),
    );

    // ── NOTICES SECTION ──
    children.push(
      new Paragraph({
        text: `1. Notices Summary (${notices.length} total)`,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
      }),
    );

    if (notices.length === 0) {
      children.push(new Paragraph({ text: 'No notices found.', spacing: { after: 200 } }));
    } else {
      // Table header
      const headerRow = new TableRow({
        tableHeader: true,
        children: ['#', 'Title', 'Category', 'Priority', 'Status', 'Created By', 'Created At', 'Start Date', 'Expiry Date', 'Views', 'Pinned', 'Edited'].map(
          (h) =>
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, size: 18 })], alignment: AlignmentType.CENTER })],
              shading: { type: ShadingType.CLEAR, fill: '2563EB', color: 'FFFFFF' },
            }),
        ),
      });

      const dataRows = notices.map((n, i) => {
        const createdAt = new Date(n.createdAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
        const startDate = new Date(n.startDate).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
        const expiryDate = new Date(n.expiryDate).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
        const editedInfo = n.isEdited && n.editedAt
          ? `Yes (${new Date(n.editedAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })})`
          : 'No';

        return new TableRow({
          children: [
            String(i + 1),
            n.title,
            n.category,
            n.priority,
            n.status,
            n.publishedBy ? `${n.publishedBy.name || n.publishedBy.userId}` : 'Unknown',
            createdAt,
            startDate,
            expiryDate,
            String(n.viewCount),
            n.isPinned ? 'Yes' : 'No',
            editedInfo,
          ].map((val) =>
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: val, size: 16 })], alignment: AlignmentType.LEFT })],
              margins: { top: 60, bottom: 60, left: 80, right: 80 },
            }),
          ),
        });
      });

      children.push(
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [headerRow, ...dataRows],
          borders: {
            top: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
            bottom: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
            left: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
            right: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
          },
        }),
      );
    }

    // ── DETAILED NOTICES ──
    children.push(
      new Paragraph({
        text: '2. Detailed Notices',
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 600, after: 200 },
      }),
    );

    notices.forEach((n, i) => {
      const createdAt = new Date(n.createdAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
      const startDate = new Date(n.startDate).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
      const expiryDate = new Date(n.expiryDate).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });

      children.push(
        new Paragraph({
          text: `${i + 1}. ${n.title}`,
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 400, after: 100 },
        }),
        new Paragraph({
          children: [new TextRun({ text: 'Description: ', bold: true }), new TextRun({ text: n.description })],
          spacing: { after: 80 },
        }),
        new Paragraph({
          children: [
            new TextRun({ text: 'Category: ', bold: true }), new TextRun({ text: n.category }),
            new TextRun({ text: '   |   Priority: ', bold: true }), new TextRun({ text: n.priority }),
            new TextRun({ text: '   |   Status: ', bold: true }), new TextRun({ text: n.status }),
          ],
          spacing: { after: 80 },
        }),
        new Paragraph({
          children: [
            new TextRun({ text: 'Created By: ', bold: true }),
            new TextRun({ text: n.publishedBy ? `${n.publishedBy.name || ''} (${n.publishedBy.userId})` : 'Unknown' }),
            new TextRun({ text: '   |   Created At: ', bold: true }),
            new TextRun({ text: createdAt }),
          ],
          spacing: { after: 80 },
        }),
        new Paragraph({
          children: [
            new TextRun({ text: 'Start Date: ', bold: true }), new TextRun({ text: startDate }),
            new TextRun({ text: '   |   Expiry Date: ', bold: true }), new TextRun({ text: expiryDate }),
          ],
          spacing: { after: 80 },
        }),
        new Paragraph({
          children: [
            new TextRun({ text: 'Pinned: ', bold: true }), new TextRun({ text: n.isPinned ? 'Yes' : 'No' }),
            new TextRun({ text: '   |   Views: ', bold: true }), new TextRun({ text: String(n.viewCount) }),
            new TextRun({ text: '   |   Likes: ', bold: true }), new TextRun({ text: String(n.likeCount) }),
            new TextRun({ text: '   |   Helpful: ', bold: true }), new TextRun({ text: String(n.helpfulCount) }),
          ],
          spacing: { after: 80 },
        }),
        ...(n.isEdited
          ? [new Paragraph({
              children: [
                new TextRun({ text: 'Last Edited: ', bold: true, color: 'D97706' }),
                new TextRun({ text: n.editedAt ? new Date(n.editedAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }) : 'Unknown', color: 'D97706' }),
              ],
              spacing: { after: 80 },
            })]
          : []),
        new Paragraph({ text: '', spacing: { after: 80 } }),
      );
    });

    // ── USER REQUESTS SECTION ──
    children.push(
      new Paragraph({
        text: `3. User Notice Requests (${requests.length} total)`,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 600, after: 200 },
      }),
    );

    if (requests.length === 0) {
      children.push(new Paragraph({ text: 'No requests found.', spacing: { after: 200 } }));
    } else {
      const reqHeaderRow = new TableRow({
        tableHeader: true,
        children: ['#', 'Title', 'Category', 'Requested By', 'Status', 'Created At'].map(
          (h) => new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, size: 18 })], alignment: AlignmentType.CENTER })],
            shading: { type: ShadingType.CLEAR, fill: '7C3AED', color: 'FFFFFF' },
          }),
        ),
      });

      const reqRows = requests.map((r, i) => {
        const createdAt = new Date(r.createdAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
        return new TableRow({
          children: [String(i + 1), r.title, r.category, r.requestedBy, (r as any).status || 'pending', createdAt].map(
            (val) => new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: val, size: 16 })] })],
              margins: { top: 60, bottom: 60, left: 80, right: 80 },
            }),
          ),
        });
      });

      children.push(
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [reqHeaderRow, ...reqRows],
          borders: {
            top: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
            bottom: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
            left: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
            right: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
          },
        }),
      );
    }

    // Footer
    children.push(
      new Paragraph({
        children: [new TextRun({ text: `--- End of Report | Generated at ${generatedAt} by ${generatedBy} ---`, size: 16, color: '888888', italics: true })],
        alignment: AlignmentType.CENTER,
        spacing: { before: 600, after: 200 },
      }),
    );

    const doc = new Document({
      sections: [{ children }],
      title: 'Notice Board Report',
      creator: generatedBy,
    });

    const buffer = await Packer.toBuffer(doc);

    // Save to disk
    const reportsDir = path.join(process.cwd(), 'download');
    if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });

    const safeDate = now.toISOString().replace(/[:.]/g, '-');
    const fileName = `report_${safeDate}.docx`;
    const filePath = path.join(reportsDir, fileName);
    fs.writeFileSync(filePath, buffer);

    // Log activity
    await db.activityLog.create({
      data: {
        action: 'generate_report',
        entityType: 'report',
        userId: user.id,
        details: JSON.stringify({ fileName, generatedAt }),
      },
    });

    return NextResponse.json({
      success: true,
      fileName,
      downloadUrl: `/api/reports/download?file=${encodeURIComponent(fileName)}`,
      savedPath: filePath,
    });
  } catch (error) {
    console.error('Generate report error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
